### ISSUE TITLE
UI of new folders looking a bit odd in Chrome

### ISSUE THREAD

**Issue by jobthomas** [FlowPress/Sidekick-Issues#1]
@raptor235 See screencast - the UI seems a bit off: turning orange on hover and not showing icons properly:

![http://cld.wthms.co/14GVy/5eDQentQ](http://cld.wthms.co/14GVy/5eDQentQ+)

**Comment by bitwit** [comment]
Thanks for bringing it to our attention. Could you confirm for me that a hard browser refresh doesn't resolve the problem? We uploaded some CSS fixes just a day ago which I hope address this.

If not, it looks like something in the WP environment is overwriting our styles. We have a forthcoming version that will isolate the builder tool and prevent this completely (by using an iframe).

**Comment by jobthomas** [comment]
The hard refresh fixed it! Sorry for the bothering :D.
